# Generated by Django 4.0.3 on 2022-05-20 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_app', '0002_unreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unreg',
        ),
    ]
