# Generated by Django 4.0.3 on 2022-05-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_app', '0004_unreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreg',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
