# Generated by Django 4.0.3 on 2022-05-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_app', '0010_alter_unreg_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='unreg',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
