# Generated by Django 4.0.3 on 2022-05-23 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_app', '0012_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unreg',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 10, 29, 9, 762001), null=True),
        ),
    ]
