# Generated by Django 4.0.3 on 2022-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric_app', '0015_alter_unreg_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='checking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='biometric_app/check')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='unreg',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
